--[TAM KOD İÇERİĞİ]--
-- Önemli: ruzgar878/babapro31 dokümanındaki tam kod yapısını buraya kopyalayın.
-- Kodun başı: _G.MarshmallowFarmActive = false; ...
-- Kodun sonu: ...Main.Visible = not Main.Visible end end)
